development:
  adapter: postgresql
  database: colchonet_dev
  host: localhost
  username: rails
  password: rails

test:
  adapter: postgresql
  database: colchonet_test
  host: localhost
  username: rails
  password: rails